// ════════════════════════════════════════════════════════════════
//   Angela's English Academy - 단어 데이터 (수준별 분류)
// ════════════════════════════════════════════════════════════════

export const WORD_LEVELS = {
  kinder: {
    id: "kinder",
    label: "유치원 (5~6세)",
    icon: "🌱",
    desc: "기초 단어 30개",
    color: "#fbcfe8",
    accent: "#ec4899"
  },
  elem1: {
    id: "elem1",
    label: "초등 저학년",
    icon: "🌿",
    desc: "쉬운 단어 50개",
    color: "#bbf7d0",
    accent: "#22c55e"
  },
  elem2: {
    id: "elem2",
    label: "초등 고학년",
    icon: "🍀",
    desc: "기본 단어 100개",
    color: "#bfdbfe",
    accent: "#4f8ef7"
  },
  middle: {
    id: "middle",
    label: "중학교",
    icon: "🌳",
    desc: "중학 수준 200개",
    color: "#ddd6fe",
    accent: "#a855f7"
  },
  all: {
    id: "all",
    label: "종합 (전체)",
    icon: "🌲",
    desc: "모든 단어 300개+",
    color: "#fed7aa",
    accent: "#f97316"
  }
};

// 카테고리 정보
export const WORD_CATEGORIES = {
  "동물": { icon: "🐶", color: "#fef3c7" },
  "음식": { icon: "🍎", color: "#fee2e2" },
  "과일": { icon: "🍓", color: "#fce7f3" },
  "색깔": { icon: "🎨", color: "#e9d5ff" },
  "숫자": { icon: "🔢", color: "#dbeafe" },
  "가족": { icon: "👨‍👩‍👧", color: "#fed7aa" },
  "학교": { icon: "🏫", color: "#bfdbfe" },
  "신체": { icon: "👁️", color: "#fbcfe8" },
  "옷": { icon: "👕", color: "#ddd6fe" },
  "날씨": { icon: "☀️", color: "#fef9c3" },
  "자연": { icon: "🌳", color: "#bbf7d0" },
  "감정": { icon: "😊", color: "#fde68a" },
  "직업": { icon: "👨‍⚕️", color: "#c7d2fe" },
  "동사": { icon: "🏃", color: "#fecaca" },
  "형용사": { icon: "✨", color: "#fed7aa" },
  "시간": { icon: "⏰", color: "#a5f3fc" },
  "장소": { icon: "🏠", color: "#d9f99d" },
  "교통": { icon: "🚗", color: "#bae6fd" },
  "취미": { icon: "🎮", color: "#fbcfe8" },
  "기타": { icon: "📦", color: "#e5e7eb" },
};

// ════════════════════════════════════════════════════════════════
// 🌱 유치원 수준 (5~6세) - 30개: 가장 쉬운 기초 단어
// ════════════════════════════════════════════════════════════════
const KINDER = [
  // 동물 (10개)
  { en: "dog", ko: "강아지", cat: "동물", level: "kinder" },
  { en: "cat", ko: "고양이", cat: "동물", level: "kinder" },
  { en: "pig", ko: "돼지", cat: "동물", level: "kinder" },
  { en: "cow", ko: "소", cat: "동물", level: "kinder" },
  { en: "duck", ko: "오리", cat: "동물", level: "kinder" },
  { en: "fish", ko: "물고기", cat: "동물", level: "kinder" },
  { en: "bird", ko: "새", cat: "동물", level: "kinder" },
  { en: "bear", ko: "곰", cat: "동물", level: "kinder" },
  { en: "lion", ko: "사자", cat: "동물", level: "kinder" },
  { en: "rabbit", ko: "토끼", cat: "동물", level: "kinder" },
  // 과일 (5개)
  { en: "apple", ko: "사과", cat: "과일", level: "kinder" },
  { en: "banana", ko: "바나나", cat: "과일", level: "kinder" },
  { en: "grape", ko: "포도", cat: "과일", level: "kinder" },
  { en: "orange", ko: "오렌지", cat: "과일", level: "kinder" },
  { en: "strawberry", ko: "딸기", cat: "과일", level: "kinder" },
  // 색깔 (5개)
  { en: "red", ko: "빨강", cat: "색깔", level: "kinder" },
  { en: "blue", ko: "파랑", cat: "색깔", level: "kinder" },
  { en: "yellow", ko: "노랑", cat: "색깔", level: "kinder" },
  { en: "green", ko: "초록", cat: "색깔", level: "kinder" },
  { en: "pink", ko: "분홍", cat: "색깔", level: "kinder" },
  // 가족 (5개)
  { en: "mom", ko: "엄마", cat: "가족", level: "kinder" },
  { en: "dad", ko: "아빠", cat: "가족", level: "kinder" },
  { en: "baby", ko: "아기", cat: "가족", level: "kinder" },
  { en: "boy", ko: "남자아이", cat: "가족", level: "kinder" },
  { en: "girl", ko: "여자아이", cat: "가족", level: "kinder" },
  // 숫자 (5개)
  { en: "one", ko: "하나", cat: "숫자", level: "kinder" },
  { en: "two", ko: "둘", cat: "숫자", level: "kinder" },
  { en: "three", ko: "셋", cat: "숫자", level: "kinder" },
  { en: "four", ko: "넷", cat: "숫자", level: "kinder" },
  { en: "five", ko: "다섯", cat: "숫자", level: "kinder" },
];

// ════════════════════════════════════════════════════════════════
// 🌿 초등 저학년 - 50개
// ════════════════════════════════════════════════════════════════
const ELEM1 = [
  // 동물 (8개)
  { en: "tiger", ko: "호랑이", cat: "동물", level: "elem1" },
  { en: "elephant", ko: "코끼리", cat: "동물", level: "elem1" },
  { en: "monkey", ko: "원숭이", cat: "동물", level: "elem1" },
  { en: "horse", ko: "말", cat: "동물", level: "elem1" },
  { en: "sheep", ko: "양", cat: "동물", level: "elem1" },
  { en: "chicken", ko: "닭", cat: "동물", level: "elem1" },
  { en: "mouse", ko: "쥐", cat: "동물", level: "elem1" },
  { en: "frog", ko: "개구리", cat: "동물", level: "elem1" },
  // 음식 (8개)
  { en: "bread", ko: "빵", cat: "음식", level: "elem1" },
  { en: "milk", ko: "우유", cat: "음식", level: "elem1" },
  { en: "water", ko: "물", cat: "음식", level: "elem1" },
  { en: "egg", ko: "달걀", cat: "음식", level: "elem1" },
  { en: "rice", ko: "밥", cat: "음식", level: "elem1" },
  { en: "cake", ko: "케이크", cat: "음식", level: "elem1" },
  { en: "candy", ko: "사탕", cat: "음식", level: "elem1" },
  { en: "ice cream", ko: "아이스크림", cat: "음식", level: "elem1" },
  // 학교 (8개)
  { en: "school", ko: "학교", cat: "학교", level: "elem1" },
  { en: "teacher", ko: "선생님", cat: "학교", level: "elem1" },
  { en: "student", ko: "학생", cat: "학교", level: "elem1" },
  { en: "book", ko: "책", cat: "학교", level: "elem1" },
  { en: "pencil", ko: "연필", cat: "학교", level: "elem1" },
  { en: "desk", ko: "책상", cat: "학교", level: "elem1" },
  { en: "chair", ko: "의자", cat: "학교", level: "elem1" },
  { en: "bag", ko: "가방", cat: "학교", level: "elem1" },
  // 가족 (6개)
  { en: "father", ko: "아버지", cat: "가족", level: "elem1" },
  { en: "mother", ko: "어머니", cat: "가족", level: "elem1" },
  { en: "brother", ko: "형/오빠/남동생", cat: "가족", level: "elem1" },
  { en: "sister", ko: "누나/언니/여동생", cat: "가족", level: "elem1" },
  { en: "grandpa", ko: "할아버지", cat: "가족", level: "elem1" },
  { en: "grandma", ko: "할머니", cat: "가족", level: "elem1" },
  // 색깔 (5개)
  { en: "black", ko: "검정", cat: "색깔", level: "elem1" },
  { en: "white", ko: "하양", cat: "색깔", level: "elem1" },
  { en: "purple", ko: "보라", cat: "색깔", level: "elem1" },
  { en: "brown", ko: "갈색", cat: "색깔", level: "elem1" },
  { en: "gray", ko: "회색", cat: "색깔", level: "elem1" },
  // 신체 (8개)
  { en: "head", ko: "머리", cat: "신체", level: "elem1" },
  { en: "eye", ko: "눈", cat: "신체", level: "elem1" },
  { en: "nose", ko: "코", cat: "신체", level: "elem1" },
  { en: "mouth", ko: "입", cat: "신체", level: "elem1" },
  { en: "ear", ko: "귀", cat: "신체", level: "elem1" },
  { en: "hand", ko: "손", cat: "신체", level: "elem1" },
  { en: "foot", ko: "발", cat: "신체", level: "elem1" },
  { en: "hair", ko: "머리카락", cat: "신체", level: "elem1" },
  // 감정 (4개)
  { en: "happy", ko: "행복한", cat: "감정", level: "elem1" },
  { en: "sad", ko: "슬픈", cat: "감정", level: "elem1" },
  { en: "angry", ko: "화난", cat: "감정", level: "elem1" },
  { en: "love", ko: "사랑", cat: "감정", level: "elem1" },
  // 숫자 (3개)
  { en: "six", ko: "여섯", cat: "숫자", level: "elem1" },
  { en: "seven", ko: "일곱", cat: "숫자", level: "elem1" },
  { en: "ten", ko: "열", cat: "숫자", level: "elem1" },
];

// ════════════════════════════════════════════════════════════════
// 🍀 초등 고학년 - 100개
// ════════════════════════════════════════════════════════════════
const ELEM2 = [
  // 동물 (12개)
  { en: "wolf", ko: "늑대", cat: "동물", level: "elem2" },
  { en: "fox", ko: "여우", cat: "동물", level: "elem2" },
  { en: "deer", ko: "사슴", cat: "동물", level: "elem2" },
  { en: "giraffe", ko: "기린", cat: "동물", level: "elem2" },
  { en: "zebra", ko: "얼룩말", cat: "동물", level: "elem2" },
  { en: "snake", ko: "뱀", cat: "동물", level: "elem2" },
  { en: "turtle", ko: "거북", cat: "동물", level: "elem2" },
  { en: "spider", ko: "거미", cat: "동물", level: "elem2" },
  { en: "butterfly", ko: "나비", cat: "동물", level: "elem2" },
  { en: "shark", ko: "상어", cat: "동물", level: "elem2" },
  { en: "whale", ko: "고래", cat: "동물", level: "elem2" },
  { en: "dolphin", ko: "돌고래", cat: "동물", level: "elem2" },
  // 음식 (12개)
  { en: "pizza", ko: "피자", cat: "음식", level: "elem2" },
  { en: "hamburger", ko: "햄버거", cat: "음식", level: "elem2" },
  { en: "chicken", ko: "치킨", cat: "음식", level: "elem2" },
  { en: "soup", ko: "수프", cat: "음식", level: "elem2" },
  { en: "salad", ko: "샐러드", cat: "음식", level: "elem2" },
  { en: "cheese", ko: "치즈", cat: "음식", level: "elem2" },
  { en: "butter", ko: "버터", cat: "음식", level: "elem2" },
  { en: "noodle", ko: "면", cat: "음식", level: "elem2" },
  { en: "fruit", ko: "과일", cat: "음식", level: "elem2" },
  { en: "vegetable", ko: "채소", cat: "음식", level: "elem2" },
  { en: "juice", ko: "주스", cat: "음식", level: "elem2" },
  { en: "tea", ko: "차", cat: "음식", level: "elem2" },
  // 학교/학용품 (10개)
  { en: "classroom", ko: "교실", cat: "학교", level: "elem2" },
  { en: "library", ko: "도서관", cat: "학교", level: "elem2" },
  { en: "eraser", ko: "지우개", cat: "학교", level: "elem2" },
  { en: "ruler", ko: "자", cat: "학교", level: "elem2" },
  { en: "scissors", ko: "가위", cat: "학교", level: "elem2" },
  { en: "notebook", ko: "공책", cat: "학교", level: "elem2" },
  { en: "homework", ko: "숙제", cat: "학교", level: "elem2" },
  { en: "lesson", ko: "수업", cat: "학교", level: "elem2" },
  { en: "test", ko: "시험", cat: "학교", level: "elem2" },
  { en: "friend", ko: "친구", cat: "학교", level: "elem2" },
  // 날씨 (8개)
  { en: "sunny", ko: "맑은", cat: "날씨", level: "elem2" },
  { en: "rainy", ko: "비 오는", cat: "날씨", level: "elem2" },
  { en: "cloudy", ko: "흐린", cat: "날씨", level: "elem2" },
  { en: "snowy", ko: "눈 오는", cat: "날씨", level: "elem2" },
  { en: "windy", ko: "바람 부는", cat: "날씨", level: "elem2" },
  { en: "hot", ko: "더운", cat: "날씨", level: "elem2" },
  { en: "cold", ko: "추운", cat: "날씨", level: "elem2" },
  { en: "warm", ko: "따뜻한", cat: "날씨", level: "elem2" },
  // 자연 (10개)
  { en: "tree", ko: "나무", cat: "자연", level: "elem2" },
  { en: "flower", ko: "꽃", cat: "자연", level: "elem2" },
  { en: "grass", ko: "풀", cat: "자연", level: "elem2" },
  { en: "mountain", ko: "산", cat: "자연", level: "elem2" },
  { en: "river", ko: "강", cat: "자연", level: "elem2" },
  { en: "sea", ko: "바다", cat: "자연", level: "elem2" },
  { en: "sky", ko: "하늘", cat: "자연", level: "elem2" },
  { en: "sun", ko: "해", cat: "자연", level: "elem2" },
  { en: "moon", ko: "달", cat: "자연", level: "elem2" },
  { en: "star", ko: "별", cat: "자연", level: "elem2" },
  // 옷 (8개)
  { en: "shirt", ko: "셔츠", cat: "옷", level: "elem2" },
  { en: "pants", ko: "바지", cat: "옷", level: "elem2" },
  { en: "shoes", ko: "신발", cat: "옷", level: "elem2" },
  { en: "hat", ko: "모자", cat: "옷", level: "elem2" },
  { en: "socks", ko: "양말", cat: "옷", level: "elem2" },
  { en: "dress", ko: "원피스", cat: "옷", level: "elem2" },
  { en: "coat", ko: "외투", cat: "옷", level: "elem2" },
  { en: "skirt", ko: "치마", cat: "옷", level: "elem2" },
  // 동사 (10개)
  { en: "go", ko: "가다", cat: "동사", level: "elem2" },
  { en: "come", ko: "오다", cat: "동사", level: "elem2" },
  { en: "eat", ko: "먹다", cat: "동사", level: "elem2" },
  { en: "drink", ko: "마시다", cat: "동사", level: "elem2" },
  { en: "run", ko: "달리다", cat: "동사", level: "elem2" },
  { en: "walk", ko: "걷다", cat: "동사", level: "elem2" },
  { en: "jump", ko: "점프하다", cat: "동사", level: "elem2" },
  { en: "sleep", ko: "자다", cat: "동사", level: "elem2" },
  { en: "read", ko: "읽다", cat: "동사", level: "elem2" },
  { en: "write", ko: "쓰다", cat: "동사", level: "elem2" },
  // 형용사 (10개)
  { en: "big", ko: "큰", cat: "형용사", level: "elem2" },
  { en: "small", ko: "작은", cat: "형용사", level: "elem2" },
  { en: "tall", ko: "키 큰", cat: "형용사", level: "elem2" },
  { en: "short", ko: "짧은/키 작은", cat: "형용사", level: "elem2" },
  { en: "long", ko: "긴", cat: "형용사", level: "elem2" },
  { en: "fast", ko: "빠른", cat: "형용사", level: "elem2" },
  { en: "slow", ko: "느린", cat: "형용사", level: "elem2" },
  { en: "new", ko: "새로운", cat: "형용사", level: "elem2" },
  { en: "old", ko: "오래된", cat: "형용사", level: "elem2" },
  { en: "good", ko: "좋은", cat: "형용사", level: "elem2" },
  // 가족 (5개)
  { en: "uncle", ko: "삼촌", cat: "가족", level: "elem2" },
  { en: "aunt", ko: "이모/고모", cat: "가족", level: "elem2" },
  { en: "cousin", ko: "사촌", cat: "가족", level: "elem2" },
  { en: "son", ko: "아들", cat: "가족", level: "elem2" },
  { en: "daughter", ko: "딸", cat: "가족", level: "elem2" },
  // 감정 (5개)
  { en: "excited", ko: "신난", cat: "감정", level: "elem2" },
  { en: "tired", ko: "피곤한", cat: "감정", level: "elem2" },
  { en: "bored", ko: "지루한", cat: "감정", level: "elem2" },
  { en: "scared", ko: "무서운", cat: "감정", level: "elem2" },
  { en: "surprised", ko: "놀란", cat: "감정", level: "elem2" },
  // 숫자 (3개)
  { en: "twenty", ko: "스물", cat: "숫자", level: "elem2" },
  { en: "hundred", ko: "백", cat: "숫자", level: "elem2" },
  { en: "thousand", ko: "천", cat: "숫자", level: "elem2" },
  // 신체 (5개)
  { en: "arm", ko: "팔", cat: "신체", level: "elem2" },
  { en: "leg", ko: "다리", cat: "신체", level: "elem2" },
  { en: "finger", ko: "손가락", cat: "신체", level: "elem2" },
  { en: "face", ko: "얼굴", cat: "신체", level: "elem2" },
  { en: "teeth", ko: "이빨", cat: "신체", level: "elem2" },
  // 기타 (2개)
  { en: "house", ko: "집", cat: "장소", level: "elem2" },
  { en: "room", ko: "방", cat: "장소", level: "elem2" },
];

// ════════════════════════════════════════════════════════════════
// 🌳 중학교 - 200개
// ════════════════════════════════════════════════════════════════
const MIDDLE = [
  // 동사 (30개)
  { en: "study", ko: "공부하다", cat: "동사", level: "middle" },
  { en: "learn", ko: "배우다", cat: "동사", level: "middle" },
  { en: "teach", ko: "가르치다", cat: "동사", level: "middle" },
  { en: "speak", ko: "말하다", cat: "동사", level: "middle" },
  { en: "listen", ko: "듣다", cat: "동사", level: "middle" },
  { en: "watch", ko: "보다", cat: "동사", level: "middle" },
  { en: "buy", ko: "사다", cat: "동사", level: "middle" },
  { en: "sell", ko: "팔다", cat: "동사", level: "middle" },
  { en: "give", ko: "주다", cat: "동사", level: "middle" },
  { en: "take", ko: "가져가다", cat: "동사", level: "middle" },
  { en: "make", ko: "만들다", cat: "동사", level: "middle" },
  { en: "think", ko: "생각하다", cat: "동사", level: "middle" },
  { en: "know", ko: "알다", cat: "동사", level: "middle" },
  { en: "remember", ko: "기억하다", cat: "동사", level: "middle" },
  { en: "forget", ko: "잊다", cat: "동사", level: "middle" },
  { en: "begin", ko: "시작하다", cat: "동사", level: "middle" },
  { en: "finish", ko: "끝내다", cat: "동사", level: "middle" },
  { en: "stop", ko: "멈추다", cat: "동사", level: "middle" },
  { en: "help", ko: "돕다", cat: "동사", level: "middle" },
  { en: "play", ko: "놀다", cat: "동사", level: "middle" },
  { en: "sing", ko: "노래하다", cat: "동사", level: "middle" },
  { en: "dance", ko: "춤추다", cat: "동사", level: "middle" },
  { en: "swim", ko: "수영하다", cat: "동사", level: "middle" },
  { en: "draw", ko: "그리다", cat: "동사", level: "middle" },
  { en: "build", ko: "짓다", cat: "동사", level: "middle" },
  { en: "carry", ko: "운반하다", cat: "동사", level: "middle" },
  { en: "throw", ko: "던지다", cat: "동사", level: "middle" },
  { en: "catch", ko: "잡다", cat: "동사", level: "middle" },
  { en: "find", ko: "찾다", cat: "동사", level: "middle" },
  { en: "lose", ko: "잃다", cat: "동사", level: "middle" },
  // 형용사 (25개)
  { en: "beautiful", ko: "아름다운", cat: "형용사", level: "middle" },
  { en: "ugly", ko: "못생긴", cat: "형용사", level: "middle" },
  { en: "young", ko: "어린", cat: "형용사", level: "middle" },
  { en: "strong", ko: "강한", cat: "형용사", level: "middle" },
  { en: "weak", ko: "약한", cat: "형용사", level: "middle" },
  { en: "rich", ko: "부유한", cat: "형용사", level: "middle" },
  { en: "poor", ko: "가난한", cat: "형용사", level: "middle" },
  { en: "easy", ko: "쉬운", cat: "형용사", level: "middle" },
  { en: "difficult", ko: "어려운", cat: "형용사", level: "middle" },
  { en: "important", ko: "중요한", cat: "형용사", level: "middle" },
  { en: "interesting", ko: "재미있는", cat: "형용사", level: "middle" },
  { en: "boring", ko: "지루한", cat: "형용사", level: "middle" },
  { en: "delicious", ko: "맛있는", cat: "형용사", level: "middle" },
  { en: "famous", ko: "유명한", cat: "형용사", level: "middle" },
  { en: "kind", ko: "친절한", cat: "형용사", level: "middle" },
  { en: "smart", ko: "똑똑한", cat: "형용사", level: "middle" },
  { en: "funny", ko: "웃긴", cat: "형용사", level: "middle" },
  { en: "lazy", ko: "게으른", cat: "형용사", level: "middle" },
  { en: "honest", ko: "정직한", cat: "형용사", level: "middle" },
  { en: "polite", ko: "예의 바른", cat: "형용사", level: "middle" },
  { en: "quiet", ko: "조용한", cat: "형용사", level: "middle" },
  { en: "noisy", ko: "시끄러운", cat: "형용사", level: "middle" },
  { en: "dangerous", ko: "위험한", cat: "형용사", level: "middle" },
  { en: "safe", ko: "안전한", cat: "형용사", level: "middle" },
  { en: "expensive", ko: "비싼", cat: "형용사", level: "middle" },
  // 직업 (15개)
  { en: "doctor", ko: "의사", cat: "직업", level: "middle" },
  { en: "nurse", ko: "간호사", cat: "직업", level: "middle" },
  { en: "police officer", ko: "경찰관", cat: "직업", level: "middle" },
  { en: "firefighter", ko: "소방관", cat: "직업", level: "middle" },
  { en: "farmer", ko: "농부", cat: "직업", level: "middle" },
  { en: "engineer", ko: "엔지니어", cat: "직업", level: "middle" },
  { en: "scientist", ko: "과학자", cat: "직업", level: "middle" },
  { en: "artist", ko: "예술가", cat: "직업", level: "middle" },
  { en: "singer", ko: "가수", cat: "직업", level: "middle" },
  { en: "actor", ko: "배우", cat: "직업", level: "middle" },
  { en: "writer", ko: "작가", cat: "직업", level: "middle" },
  { en: "cook", ko: "요리사", cat: "직업", level: "middle" },
  { en: "driver", ko: "운전사", cat: "직업", level: "middle" },
  { en: "lawyer", ko: "변호사", cat: "직업", level: "middle" },
  { en: "soldier", ko: "군인", cat: "직업", level: "middle" },
  // 시간 (15개)
  { en: "morning", ko: "아침", cat: "시간", level: "middle" },
  { en: "afternoon", ko: "오후", cat: "시간", level: "middle" },
  { en: "evening", ko: "저녁", cat: "시간", level: "middle" },
  { en: "night", ko: "밤", cat: "시간", level: "middle" },
  { en: "today", ko: "오늘", cat: "시간", level: "middle" },
  { en: "tomorrow", ko: "내일", cat: "시간", level: "middle" },
  { en: "yesterday", ko: "어제", cat: "시간", level: "middle" },
  { en: "week", ko: "주", cat: "시간", level: "middle" },
  { en: "month", ko: "월/달", cat: "시간", level: "middle" },
  { en: "year", ko: "년", cat: "시간", level: "middle" },
  { en: "hour", ko: "시간", cat: "시간", level: "middle" },
  { en: "minute", ko: "분", cat: "시간", level: "middle" },
  { en: "second", ko: "초", cat: "시간", level: "middle" },
  { en: "spring", ko: "봄", cat: "시간", level: "middle" },
  { en: "summer", ko: "여름", cat: "시간", level: "middle" },
  // 장소 (15개)
  { en: "hospital", ko: "병원", cat: "장소", level: "middle" },
  { en: "park", ko: "공원", cat: "장소", level: "middle" },
  { en: "store", ko: "가게", cat: "장소", level: "middle" },
  { en: "market", ko: "시장", cat: "장소", level: "middle" },
  { en: "restaurant", ko: "식당", cat: "장소", level: "middle" },
  { en: "bank", ko: "은행", cat: "장소", level: "middle" },
  { en: "church", ko: "교회", cat: "장소", level: "middle" },
  { en: "post office", ko: "우체국", cat: "장소", level: "middle" },
  { en: "airport", ko: "공항", cat: "장소", level: "middle" },
  { en: "station", ko: "역", cat: "장소", level: "middle" },
  { en: "city", ko: "도시", cat: "장소", level: "middle" },
  { en: "town", ko: "마을", cat: "장소", level: "middle" },
  { en: "country", ko: "나라/시골", cat: "장소", level: "middle" },
  { en: "beach", ko: "해변", cat: "장소", level: "middle" },
  { en: "museum", ko: "박물관", cat: "장소", level: "middle" },
  // 교통 (10개)
  { en: "car", ko: "자동차", cat: "교통", level: "middle" },
  { en: "bus", ko: "버스", cat: "교통", level: "middle" },
  { en: "train", ko: "기차", cat: "교통", level: "middle" },
  { en: "airplane", ko: "비행기", cat: "교통", level: "middle" },
  { en: "ship", ko: "배", cat: "교통", level: "middle" },
  { en: "bicycle", ko: "자전거", cat: "교통", level: "middle" },
  { en: "subway", ko: "지하철", cat: "교통", level: "middle" },
  { en: "taxi", ko: "택시", cat: "교통", level: "middle" },
  { en: "truck", ko: "트럭", cat: "교통", level: "middle" },
  { en: "boat", ko: "보트", cat: "교통", level: "middle" },
  // 취미 (10개)
  { en: "music", ko: "음악", cat: "취미", level: "middle" },
  { en: "movie", ko: "영화", cat: "취미", level: "middle" },
  { en: "game", ko: "게임", cat: "취미", level: "middle" },
  { en: "sport", ko: "운동", cat: "취미", level: "middle" },
  { en: "soccer", ko: "축구", cat: "취미", level: "middle" },
  { en: "baseball", ko: "야구", cat: "취미", level: "middle" },
  { en: "basketball", ko: "농구", cat: "취미", level: "middle" },
  { en: "reading", ko: "독서", cat: "취미", level: "middle" },
  { en: "painting", ko: "그림 그리기", cat: "취미", level: "middle" },
  { en: "travel", ko: "여행", cat: "취미", level: "middle" },
  // 음식 (10개)
  { en: "breakfast", ko: "아침식사", cat: "음식", level: "middle" },
  { en: "lunch", ko: "점심식사", cat: "음식", level: "middle" },
  { en: "dinner", ko: "저녁식사", cat: "음식", level: "middle" },
  { en: "meat", ko: "고기", cat: "음식", level: "middle" },
  { en: "sugar", ko: "설탕", cat: "음식", level: "middle" },
  { en: "salt", ko: "소금", cat: "음식", level: "middle" },
  { en: "coffee", ko: "커피", cat: "음식", level: "middle" },
  { en: "potato", ko: "감자", cat: "음식", level: "middle" },
  { en: "tomato", ko: "토마토", cat: "음식", level: "middle" },
  { en: "onion", ko: "양파", cat: "음식", level: "middle" },
  // 자연/날씨 (10개)
  { en: "weather", ko: "날씨", cat: "날씨", level: "middle" },
  { en: "rain", ko: "비", cat: "날씨", level: "middle" },
  { en: "snow", ko: "눈", cat: "날씨", level: "middle" },
  { en: "wind", ko: "바람", cat: "날씨", level: "middle" },
  { en: "cloud", ko: "구름", cat: "날씨", level: "middle" },
  { en: "storm", ko: "폭풍", cat: "날씨", level: "middle" },
  { en: "forest", ko: "숲", cat: "자연", level: "middle" },
  { en: "lake", ko: "호수", cat: "자연", level: "middle" },
  { en: "ocean", ko: "대양", cat: "자연", level: "middle" },
  { en: "island", ko: "섬", cat: "자연", level: "middle" },
  // 감정 (10개)
  { en: "feel", ko: "느끼다", cat: "감정", level: "middle" },
  { en: "worry", ko: "걱정하다", cat: "감정", level: "middle" },
  { en: "hope", ko: "희망", cat: "감정", level: "middle" },
  { en: "fear", ko: "두려움", cat: "감정", level: "middle" },
  { en: "joy", ko: "기쁨", cat: "감정", level: "middle" },
  { en: "anger", ko: "분노", cat: "감정", level: "middle" },
  { en: "proud", ko: "자랑스러운", cat: "감정", level: "middle" },
  { en: "shy", ko: "수줍은", cat: "감정", level: "middle" },
  { en: "lonely", ko: "외로운", cat: "감정", level: "middle" },
  { en: "nervous", ko: "긴장한", cat: "감정", level: "middle" },
  // 학교 (10개)
  { en: "subject", ko: "과목", cat: "학교", level: "middle" },
  { en: "math", ko: "수학", cat: "학교", level: "middle" },
  { en: "science", ko: "과학", cat: "학교", level: "middle" },
  { en: "history", ko: "역사", cat: "학교", level: "middle" },
  { en: "art", ko: "미술", cat: "학교", level: "middle" },
  { en: "music class", ko: "음악 시간", cat: "학교", level: "middle" },
  { en: "grade", ko: "학년/성적", cat: "학교", level: "middle" },
  { en: "exam", ko: "시험", cat: "학교", level: "middle" },
  { en: "answer", ko: "답", cat: "학교", level: "middle" },
  { en: "question", ko: "질문", cat: "학교", level: "middle" },
  // 기타 (40개)
  { en: "world", ko: "세상", cat: "기타", level: "middle" },
  { en: "country", ko: "국가", cat: "기타", level: "middle" },
  { en: "language", ko: "언어", cat: "기타", level: "middle" },
  { en: "people", ko: "사람들", cat: "기타", level: "middle" },
  { en: "child", ko: "아이", cat: "기타", level: "middle" },
  { en: "adult", ko: "어른", cat: "기타", level: "middle" },
  { en: "name", ko: "이름", cat: "기타", level: "middle" },
  { en: "age", ko: "나이", cat: "기타", level: "middle" },
  { en: "money", ko: "돈", cat: "기타", level: "middle" },
  { en: "job", ko: "직업/일", cat: "기타", level: "middle" },
  { en: "work", ko: "일하다", cat: "기타", level: "middle" },
  { en: "life", ko: "삶", cat: "기타", level: "middle" },
  { en: "love", ko: "사랑하다", cat: "기타", level: "middle" },
  { en: "friend", ko: "친구", cat: "기타", level: "middle" },
  { en: "letter", ko: "편지", cat: "기타", level: "middle" },
  { en: "story", ko: "이야기", cat: "기타", level: "middle" },
  { en: "news", ko: "뉴스", cat: "기타", level: "middle" },
  { en: "phone", ko: "전화", cat: "기타", level: "middle" },
  { en: "computer", ko: "컴퓨터", cat: "기타", level: "middle" },
  { en: "Internet", ko: "인터넷", cat: "기타", level: "middle" },
  { en: "email", ko: "이메일", cat: "기타", level: "middle" },
  { en: "address", ko: "주소", cat: "기타", level: "middle" },
  { en: "place", ko: "장소", cat: "기타", level: "middle" },
  { en: "thing", ko: "물건", cat: "기타", level: "middle" },
  { en: "way", ko: "길/방법", cat: "기타", level: "middle" },
  { en: "idea", ko: "생각", cat: "기타", level: "middle" },
  { en: "problem", ko: "문제", cat: "기타", level: "middle" },
  { en: "answer", ko: "답", cat: "기타", level: "middle" },
  { en: "color", ko: "색깔", cat: "기타", level: "middle" },
  { en: "shape", ko: "모양", cat: "기타", level: "middle" },
  { en: "size", ko: "크기", cat: "기타", level: "middle" },
  { en: "number", ko: "숫자", cat: "기타", level: "middle" },
  { en: "voice", ko: "목소리", cat: "기타", level: "middle" },
  { en: "sound", ko: "소리", cat: "기타", level: "middle" },
  { en: "music", ko: "음악", cat: "기타", level: "middle" },
  { en: "song", ko: "노래", cat: "기타", level: "middle" },
  { en: "picture", ko: "그림/사진", cat: "기타", level: "middle" },
  { en: "video", ko: "영상", cat: "기타", level: "middle" },
  { en: "key", ko: "열쇠", cat: "기타", level: "middle" },
  { en: "door", ko: "문", cat: "기타", level: "middle" },
];

// 전체 단어 합치기 (중복 제거)
const seen = new Set();
const allWords = [];
[...KINDER, ...ELEM1, ...ELEM2, ...MIDDLE].forEach(w => {
  if (!seen.has(w.en)) {
    seen.add(w.en);
    allWords.push(w);
  }
});

export const ALL_WORDS = allWords;

// 수준별 단어 가져오기 함수
export function getWordsByLevel(levelId) {
  if (levelId === "all") return ALL_WORDS;
  if (levelId === "kinder") return ALL_WORDS.filter(w => w.level === "kinder");
  if (levelId === "elem1") return ALL_WORDS.filter(w => w.level === "kinder" || w.level === "elem1");
  if (levelId === "elem2") return ALL_WORDS.filter(w => w.level === "kinder" || w.level === "elem1" || w.level === "elem2");
  if (levelId === "middle") return ALL_WORDS;
  return ALL_WORDS;
}
